# Site settings
title: CITE Tools
issues: http://github..
description: "CITE tools"
baseurl: file:///Users/lbermudez/Documents/Dropbox/github/cite/docs/_site
url: "http://github.com/opengeospatial/cite"
twitter_username: opengeospatial
github_url: "opengeospatial/cite"

# Build settings
markdown: kramdown
permalink: pretty


