# Site settings
title: CITE Tools
issues: http://github..
description: "CITE tools"
baseurl: http://opengeospatial.github.io/cite/
url: "http://opengeospatial.github.io/cite/"
twitter_username: opengeospatial
github_url: "opengeospatial/cite"

# Build settings
markdown: kramdown
permalink: pretty


